### ISSUE TITLE
right click options not working

### ISSUE THREAD

**Issue by chenks** [YodaDaCoda/chrome-deluge-remote#10]
i have enabled right click context menu options, but nothing shows up on the menu
chrome 64bit mac.

so, what's the problem?

**Comment by YodaDaCoda** [comment]
Should be fixed in 2036a1609821f6b289e681ae6b93d2a140888620.

**Comment by chenks** [comment]
the settings are not being saved.
i uninstalled the extension, re-installed the new version.
ticked all three boxes in link handling, clicked apply then save.
came out of extension settings, went back in and they were unticked again.

this can be replicated over and over again.

**Comment by YodaDaCoda** [comment]
Oops! 32282f68bf9c23794c7db7eaf8afc9151fee88ea
