### ISSUE TITLE
No data shown or Connection failed

### ISSUE THREAD

**Issue by JHPArizona** [YodaDaCoda/chrome-deluge-remote#11]
Running current version of 1.1.0. Most of the time the Remote Deluge window will pop-up the first time with a connection issue. I suspect this is a time-out issue during the login phase. Subsequently, the window will open but with no data displayed. I have left it a while (a couple of  min) but no data ever fills in. If I click out of the window back to browser and then open again, still no data. I have set and checked the login info on the options page several times. I ASSUME it is reading that OK since I do not get connection error messages after the first time (or after a long while of not have the remote deluge window open)
1. How long should it take to populate the window?
2. on the options page it has room for the host and port and a folder after the port. Is a folder specification mandatory?

I have the web interface working and can login from a browser and view / add torrents.

**Comment by YodaDaCoda** [comment]
Can you check the filters and ensure they're not hiding torrents?

**Comment by JHPArizona** [comment]
I am not sure what you are asking. If you are asking about the deluge-remote screen, there is nothing shown in the filter drop downs even when clicking on the down arrow. On Deluge, I have filters for State: All, Seeding, Paused; Tracker Host; just the one tractor; Label: multiple. In the label section I have several with all showing torrents except not_run_yet. The currently selected filters State: All; Tracker Host: All, Label: All.  On deluge-remote all the counters show zero.There are over 1000 torrents running in deluged on the server box. The server box is in my home as is the laptop that I am trying to connect with. 
Let me know if you need any other info. 
Date: Tue, 15 Sep 2015 17:01:08 -0700

**Comment by YodaDaCoda** [comment]
Could you please enable debug mode in the settings and give me a copy of the console output (preferably by pastebin)?

**Comment by JHPArizona** [comment]
Maybe I am just not understanding or maybe that is something else that is going wrong. I enabled debug and then clicked on the browser icon to show the remote deluge window. It opens as before with no data and shows no difference from the non-debug start-up. Is there supposed to be some other windows or something in debug? Which leaves me with "what console output" are you wanting me to post on pastebin?

Date: Fri, 18 Sep 2015 01:24:55 -0700

**Comment by JHPArizona** [comment]
As a try, I removed and added Remote Deluge. Still same situation of window opens with no data. Counters at top of screen all read 0. Connecting to deluge WebUI with Chrome shows the torrents. I am running Windows 7 32bit. Chrome version is 45.0.2454.93 m

**Comment by JHPArizona** [comment]
OK, I have moved on. If there is anything you would like me to do or test, please feel free to contact me.

**Comment by JHPArizona** [comment]
OK, that is one way to take care of the problem, wait till the person has given up and then just close the case :)
