### ISSUE TITLE
New user - nothing works

### ISSUE THREAD

**Issue by exile259** [YodaDaCoda/chrome-deluge-remote#12]
I just installed v1.1.  I can log into Deluge via Chrome with no issues, but I have no right click options and it will not connect to my server using either url or ip.  Suggestions?

**Comment by YodaDaCoda** [comment]
Missing right-click options is a known bug. #10 

I might need a debug log to figure out why it's not connecting. Could you provide a screenshot of your settings page?

Sorry for the delay, but I don't have much time to work on this right now.
