### ISSUE TITLE
Could not connect to Deluge!

### ISSUE THREAD

**Issue by xelfer** [YodaDaCoda/chrome-deluge-remote#15]
Hi, I have a new install of Deluge on a fresh Ubuntu 16.04 server, Deluge 1.3.12.

I've set up pointing it at my server: https://i.imgur.com/Za7SKJv.png

But I still get the error "Could not connect to Deluge". Any ideas?

I have the same settings in the "DelugeSiphon" app and that one works (after a browser restart). 

Thanks

**Comment by YodaDaCoda** [comment]
If you go to that address (http://192.168.0.1:8112) do you get the Deluge webUI?

**Comment by xelfer** [comment]
Yep: https://i.imgur.com/BEERZFg.png

**Comment by xelfer** [comment]
Any way I can help debug/test this?

**Comment by YodaDaCoda** [comment]
Could you inspect the background page and give me a copy of the debug log printed there?

**Comment by xelfer** [comment]
Is that a right click > inspect on the addon popup? if so, https://gist.github.com/94d7e6c14d07991169627171993c16d9

I also found this error:
`jQuery.Deferred exception: Cannot read property 'checkStatus' of null TypeError: Cannot read property 'checkStatus' of null
    at checkStatus (chrome-extension://epcolmlaegimilnokaddncgmdafacohf/js/popup.js:392:28)
    at HTMLDocument.<anonymous> (chrome-extension://epcolmlaegimilnokaddncgmdafacohf/js/popup.js:456:2)
    at j (chrome-extension://epcolmlaegimilnokaddncgmdafacohf/js/libs/jquery-3.0.0.min.js:2:29588)
    at k (chrome-extension://epcolmlaegimilnokaddncgmdafacohf/js/libs/jquery-3.0.0.min.js:2:29902) undefined`

**Comment by YodaDaCoda** [comment]
Go to chrome://extensions/ and check "Developer mode", then click "Inspect views: background page". Give me whatever it's printing to the "Console" tab in that window.

**Comment by xelfer** [comment]
https://i.imgur.com/2A4gAh9.png

**Comment by YodaDaCoda** [comment]
I think I've fixed it. I'll push a new version to the web store soon. I'll report back here when done.

**Comment by xelfer** [comment]
Thanks, really appreciate it :smile:

**Comment by YodaDaCoda** [comment]
Okay I've pushed v1.2.3 to the webstore. It could take up to an hour to become visible.

**Comment by xelfer** [comment]
Got it! working great now. Thank you!

**Comment by YodaDaCoda** [comment]
Glad it works! Happy to help
