### ISSUE TITLE
Deluge 1.3.14 breaks the extension

### ISSUE THREAD

**Issue by DrSeussFreak** [YodaDaCoda/chrome-deluge-remote#17]
I upgraded to the latest Deluge version, 1.3.14, and now your extension no longer works.

**Comment by chandlben** [comment]
Same problem here. Although I'm not able to view Deluge in Chrome at all so not sure if that's related or not.

**Comment by DrSeussFreak** [comment]
I can still connect through the Deluge WebUI, and Deluge Siphon works (as a temp replacement extension), but I missed Remote Deluge, it was the best.

**Comment by YodaDaCoda** [comment]
Turns out this is a 'security' check in the latest version of deluge. The contentType header needs to be set to 'application/json' on the ajax request.

http://forum.deluge-torrent.org/viewtopic.php?f=7&t=54428

**Comment by DrSeussFreak** [comment]
This makes me happy on 2 fronts, I use Remote Deluge and I use TransDrone, so hopefully fixes for both will be forthcoming!

**Comment by chandlben** [comment]
Well, updated Chrome and back in the game it would seem.

**Comment by chandlben** [comment]
So it worked for a bit, but now I'm back to square one. I'm running 1.3.14 through an Apache Reverse Proxy [setup here](http://dev.deluge-torrent.org/wiki/UserGuide/WebUI/ReverseProxy). I've turned on debug mode and the console shows:

    debug_log.js:3 Deluge: Checking status
    jquery-3.0.0.min.js:4 POST https://myurl:myport/deluge/json 500 (Internal Server Error)
    send @ jquery-3.0.0.min.js:4
    ajax @ jquery-3.0.0.min.js:4
    (anonymous) @ deluge.js:59
    Deferred @ jquery-3.0.0.min.js:2
    Deluge.api @ deluge.js:23
    pub.checkStatus @ background.js:113
    checkStatus @ js/popup.js:392
    (anonymous) @ js/popup.js:456
    j @ jquery-3.0.0.min.js:2
    k @ jquery-3.0.0.min.js:2
    debug_log.js:3 Unknown error occured
    debug_log.js:3 Extension deactivated

It's strange how it worked for a very short time, then despite making no changes, it stopped.

**Comment by DrSeussFreak** [comment]
so I see TransDrone and other apps have been fixed, do we know if this will be patched, and if so, when?

**Comment by YodaDaCoda** [comment]
I've pushed a fix to master - please test and let me know if it works.

**Comment by Terehi** [comment]
It works, thank you for fixing it. Tested it with Chrome 57 and Deluge 1.3.14.

**Comment by DrSeussFreak** [comment]
Also worked for me, same versions

**Comment by YodaDaCoda** [comment]
Fixed in latest release v1.2.4
